#Manage Puppet Module dependencies with librarian-puppet

forge 'http://forge.puppetlabs.com'

mod 'dc_impfw',
	:git => 'git://github.com/eduardodicarte/dc_impdfw.git'

mod 'dc_impdb',
	:git => 'git://github.com/eduardodicarte/dc_impdb.git'

